#!/bin/bash

myhostname=$(hostname)
myOS=$(source /etc/os-release && echo $PRETTY_NAME)
myuptime=$(uptime -p)
myusername=$USER
mydate=$(date)
mycpu=$(sudo lshw -class processor | grep -m1 product)
mycpuspeed=$(lscpu | awk -F': ' '/BogoMIPS/ {print $2}')
myram=$(free -h | awk '/Mem:/ {print $2}')
mydisks=$(lsblk -dbo NAME,MODEL,SIZE | sed 's/^/Disk(s): /')
myvideo=$(lspci | grep -i 'VGA compatible controller' | awk -F': ' '{print $2}')
myFQDN=$(hostname -f)
myhostaddress=$(hostname -I | awk '{print $1}')
mygatewayip=$(ip r | awk '/default via/ {print $3}')
mydnsserver=$(cat /etc/resolv.conf | awk '/nameserver/ {print $2}')
'''myinterfacename=$(ip a | awk '/state UP/ {print $2}' | cut -d':' -f1)
myipaddress=$(ip -o -4 addr show eth0 | awk '{print $4}')'''
'''myinterfacename=$("ens34")
myipaddress=$(ifconfig $myinterfacename | awk '/inet / {print $2}')'''
myuserslog=$(who | cut -d' ' -f1 | sort | uniq)
mydiskspace=$(df -h --output=target,avail | tail -n+2)
myprocesscount=$(ps -e --no-headers | wc -l)
myloadaverages=$(uptime | awk -F'average: ' '{print $2}')
mymemoryallocation=$(free -h --si | awk '/Mem:/ {print $3\"/\"$2}')
mylisteningports=$(ss -tunl | awk '/LISTEN/ {print $5}' | awk -F\":\" '{print $2}')
myufwrules=$(sudo ufw show raw)

cat <<sysinfo
System Report generated by $myusername, $mydate

System Information
------------------
Hostname: $myhostname
OS:$myOS
Uptime: $myuptime

Hardware Information
--------------------
cpu:$mycpu
Speed:$mycpuspeed
Ram:$myram
Disk(s):$mydisks
Video:$myvideo

Network Information
-------------------
FQDN:$myFQDN
Host Address:$myhostaddress
Gateway IP:$mygatewayip
DNS Server:$mydnsserver
InterfaceName:$myinterfacename
IP Address:$myipaddress

System Status
-------------
Users Logged In:$myuserslog
Disk Space:$mydiskspace
Process Count:$myprocesscount
Load Averages:$myloadaverages
Memory Allocation:$mymemoryallocation
Listening Network Ports:$mylisteningports
UFW Rules:$myufwrules
sysinfo


